server:
  port: 8080
#  servlet:
#    context-path: /pet

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=WebBanThuCung;encrypt=false
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail:
    host: smtp.gmail.com
    port: 587
    username: hunghung2k4123@gmail.com
    password: hukm xrqg gsvw ihmi
    properties:
      mail:
        auth: true
        starttls:
          enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
  properties:
    hibernate:
      format_sql: true

#mk: hukm xrqg gsvw ihmi
#  spring:
#    datasource:
#      url: "jdbc:mysql://localhost:3306/WebBanThuCung"
#      username: root
#      password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#  hibernate:
#      ddl-auto: update
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQLDialect

#jwt:
#  signerKey: "fqqWWh6OT+c49kLEbAL5FnWKt/7TZ0yjS+ZFPoMSV/gltKBzR2RjlTrhucriSwe9"
